substitutions:
  device_name: p1reader
  friendly_name: P1 Reader

esphome:
  name: ${device_name}s
  friendly_name: ${friendly_name}

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: ${device_name}

captive_portal:

uart:
  id: uart_dsmr
  rx_pin:
    number: GPIO20
    inverted: true
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 1700

dsmr:
  uart_id: uart_dsmr
  crc_check: false
  request_pin: GPIO4
  max_telegram_length: 1700

sensors:
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s

  - platform: dsmr
    energy_delivered_tariff1:
      id: dsmr_electricity_delivered_1
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_returned_tariff1:
      id: dsmr_electricity_returned_1
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      id: dsmr_electricity_delivered_2
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff2:
      id: dsmr_electricity_returned_2
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      id: dsmr_electricity_currently_delivered
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      id: dsmr_electricity_currently_returned
      name: "Power Produced"
      accuracy_decimals: 3
    voltage_l1:
      id: dsmr_phase_voltage_l1
      name: "Voltage Phase 1"
    voltage_l2:
      id: dsmr_phase_voltage_l2
      name: "Voltage Phase 2"
    voltage_l3:
      id: dsmr_phase_voltage_l3
      name: "Voltage Phase 3"
    current_l1:
      id: dsmr_phase_power_current_l1
      name: "Current Phase 1"
    current_l2:
      id: dsmr_phase_power_current_l2
      name: "Current Phase 2"
    current_l3:
      id: dsmr_phase_power_current_l3
      name: "Current Phase 3"
    power_delivered_l1:
      id: dsmr_phase_currently_delivered_l1
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      id: dsmr_phase_currently_delivered_l2
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      id: dsmr_phase_currently_delivered_l3
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      id: dsmr_phase_currently_returned_l1
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      id: dsmr_phase_currently_returned_l2
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      id: dsmr_phase_currently_returned_l3
      name: "Power Produced Phase 3"
      accuracy_decimals: 3

text_sensor:
  - platform: dsmr
    identification:
      name: "${friendly_name} DSMR Identification"
    p1_version:
      name: "${friendly_name} DSMR Version"
    timestamp:
      id: dsmr_timestamp
      internal: true
